### PR TITLE
README Changes for 22Q4 Release

### PR DESCRIPTION
**Pull request by danforbes**
README changes for 22Q4 release. The rendered document can be seen here https://github.com/ChainSafe/gossamer/blob/dfo/readme/README.md.

## Primary Reviewer

@timwu20

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -31,56 +31,164 @@
...
+To get started with Gossamer, follow the steps below to build the source code
+and start a development network.
 
 ### Prerequisites
 
-Install Go version [`>=1.18`](https://go.dev/dl/#go1.18)
+[Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) is required
+to acquire the Gossamer source code, and
+[Make](https://tilburgsciencehub.com/building-blocks/configure-your-computer/automation-and-workflows/make/)
+is used to build it. Building Gossamer requires version 1.18 or greater of
```
Comment (qdm12) [inline README.md:56]: It doesn't work with Go 1.19, this is blocked by #2794 then #2788 then #2719 (each blocked sequentially). Although each just need reviews really, they should be good to go.

```suggestion
is used to build it. Building Gossamer requires version 1.18 of 
```

File: README.md [hunk 2]
```diff
@@ -31,56 +31,164 @@
...
+GOARCH="amd64"
+CGO_ENABLED="1"
+```
+
+## Use Gossamer
+
+> **Warning**
+>
+> Gossamer is currently unable to build blocks due to a
+> [known issue with parachain inherents](https://github.com/ChainSafe/gossamer/issues/2937).
```
Comment (timwu20) [inline README.md:103]:
```suggestion
> Gossamer is currently unable to build blocks on Polkadot runtimes due to a
> [known issue with parachain inherents](https://github.com/ChainSafe/gossamer/issues/2937).
```

File: README.md [hunk 3]
```diff
@@ -31,56 +31,164 @@
...
 undefined: cWasmerValueTag
 ```
 
-Make sure you have the following Golang enviroment variables:
+If so, set the following
+[Golang environment variables](https://pkg.go.dev/cmd/go#hdr-Environment_variables):
+
+```
+GOARCH="amd64"
+CGO_ENABLED="1"
```
Comment (qdm12) [inline README.md:95]: This should be set for all platforms, not just apple silicon, so I'd remove from here?

```suggestion
```

File: README.md (hunk 2 above)
Comment (danforbes) [reply README.md:103]: I'm not crazy about this addition. I think it confuses the idea that Gossamer is a Polkadot Host.

File: README.md [hunk 4]
```diff
@@ -31,56 +31,164 @@
...
+We take all security issues seriously, if you believe you have found a security
+issue within a ChainSafe project please notify us immediately. If an issue is
+confirmed, we will take all necessary precautions to ensure a statement and
+patch release is made in a timely manner.
+
+### Reporting a Security Bug
+
+Please email us a description of the flaw and any related information (e.g.
+reproduction steps, version) to
+[security at chainsafe dot io](mailto:security@chainsafe.io).
```
[the remark this answers is not in the document]
Comment (danforbes) [reply README.md:180]: This is something I just copied-and-pasted. I assume it's something set at the company-level, and I have no desire to try to convince anyone it needs to be changed.

File: README.md [hunk 5]
```diff
@@ -94,11 +202,15 @@ To start the development node:
 ./bin/gossamer --chain dev
 ```
 
-The development node is configured to produce a block every slot and to finalise a block every round (as there is only one authority, `alice`.)
+The development node is configured to produce a block every slot and to finalise
+a block every round (as there is only one authority, `alice`.)
```
[the remark this answers is not in the document]
Comment (danforbes) [reply README.md:206]: This is because of the "Prettier" commit. Just view the diffs of the other commit 😉

File: README.md [hunk 6]
```diff
@@ -31,56 +31,164 @@
...
 
 ```
 make gossamer
 ```
 
-### Troubleshooting for Apple Silicon users
+Or build Gossamer _and_ move the resulting executable to `$GOPATH/bin`:
+
+```
+make install
```
[the remark this answers is not in the document]
Comment (danforbes) [reply README.md:77]: Will this get the `main` branch?

**Comment by timwu20** [comment]
@danforbes can we undraft this and merge this in before the release?

**Review by jimjbrettj — APPROVED** [review]
Looks great!

**Review by EclesioMeloJunior — APPROVED** [review]

**Review by timwu20 — APPROVED** [review]
